export default {
  isDark: false,
  colors: {
    primary: "#FFFFFF",
    secondary: "#B4B4B8",
    background: "#FFFFFF",
    title: "#1E1E1E",
    text: "#1E1E1E",
    description: "#B4B4B8",
    placeholder: "#B4B4B8",
    input: "#E7E7E7",
    icon: "#1E1E1E",
    ripple: "#DDD9D9",
    primaryWhite: "#FFFFFF",
    primaryPurple: "#7A1CAC",
    secondaryPurple: "#AD49E1",
    tertiaryPurple: "#EBD3F8",
    primaryRed: "#E72929",
    primaryGreen: "#2ECC71",
  },
};
